### ISSUE TITLE
Add structure for all languages & frameworks

### ISSUE THREAD

**Issue by svasenkov** [allure-examples/allure-examples#22]

**Comment by aleksandr-kotlyar** [comment]
Now repository looks like this:
![image](https://user-images.githubusercontent.com/17043964/110332317-3bcd5f80-8031-11eb-84e3-bdf46eccf099.png)

I suggest we need to consider what do we want. There are some different sctructures which could help organize the repository.
Here are some examples:
1. Flat structure
   allure-examples/allure-java-commons
   allure-examples/allure-java-cucumber5-junit4
   allure-examples/allure-java-cucumber5-testng
   allure-examples/allure-java-junit4
   allure-examples/allure-java-junit5
   allure-examples/allure-java-testng
   allure-examples/allure-javascript-codeceptjs
   allure-examples/allure-javascript-cucumberjs
   allure-examples/allure-javascript-jest
   allure-examples/allure-javascript-typescript
   allure-examples/allure-python-behave
   allure-examples/allure-python-pytest
2. Group by language structure
   allure-examples/allure-java/...
   allure-examples/allure-javascript/allure-javascript-codeceptjs
   allure-examples/allure-javascript/allure-javascript-cucumberjs
   allure-examples/allure-javascript/allure-javascript-jest
   allure-examples/allure-python/allure-python-behave
   allure-examples/allure-python/allure-python-pytest

|StructureType|Pros|Cons|
|-|-|-|
|Flat|Looks simple| A lot of items inone directory|
| |Easy to maintain| |
|Group|Looks more organized|Harder to maintain|

I see that here is a flat structure for java frameworks and group structure for python and javascript frameworks. We need to choose one.

I vote for the Flat structure.

**Comment by aleksandr-kotlyar** [comment]
Votes for Group structure here. If you vote for this, please describe your pros from Group structure and Cons on Flat structure.

**Comment by svasenkov** [comment]
Vote for Flat

**Comment by simple-elf** [comment]
I'm also was voting for a Flat structure, but only java need 5-6 folders, so maybe Group is better

**Comment by aleksandr-kotlyar** [comment]
I have thought about it and I think it's possible to have a group structure for monorepo, but mini-repo will be for each tool set of frameworks. It should be ensured by manual setup workflows in github actions.
