### ISSUE TITLE
Allure spock2 example

### ISSUE THREAD

**Issue by alexmjames** [allure-examples/allure-examples#38]
Hi @baev , 
Could you please include an example for allure spock2 integration that successfully process given-when-then blocks, attachments, passed, failed & ignored tests, tests with Spock tables (data driven). 

I tried various combinations of pom.xml by looking at junit5, junit4, testng etc.. configurations. But none of them resulted in a report that caters all the above Spock features. In most cases it fails to parse the given-when-then blocks. Also fails to show ignored tests. 

Please help.

**Comment by baev** [comment]
fixed in https://github.com/allure-examples/allure-spock2-gradle-kts
